/**
 * Shared question-type labels for Slate — the outline list, Add popover and
 * Inspector. The icons are line SVGs in components/TypeIcon.tsx (ADR-063).
 */

import type { Question, QuestionType } from '@/index.js';

export const TYPE_LABEL: Record<Question['type'], string> = {
  welcome: 'Welcome Screen',
  statement: 'Statement',
  thanks: 'Thank You Screen',
  short_text: 'Short Text',
  long_text: 'Long Text',
  email: 'Email',
  phone: 'Phone',
  url: 'Website',
  number: 'Number',
  date: 'Date',
  file_upload: 'File Upload',
  single_choice: 'Single Choice',
  multi_choice: 'Multi Choice',
  dropdown: 'Dropdown',
  picture_choice: 'Picture Choice',
  ranking: 'Ranking',
  matrix: 'Matrix',
  yes_no: 'Yes / No',
  legal: 'Legal / Consent',
  scale: 'Scale',
  nps: 'NPS (0–10)',
  contact_info: 'Contact Info',
  address: 'Address',
  signature: 'Signature',
  image_pin: 'Pin the Spot',
  voice_note: 'Voice Note',
  location: 'Location',
  photo_checklist: 'Photo Checklist',
  availability: 'Availability',
  review: 'Review Screen',
};

export const ADDABLE_TYPES: ReadonlyArray<{ type: QuestionType; label: string; group: string }> = [
  { type: 'short_text', label: TYPE_LABEL.short_text, group: 'Inputs' },
  { type: 'long_text', label: TYPE_LABEL.long_text, group: 'Inputs' },
  { type: 'contact_info', label: TYPE_LABEL.contact_info, group: 'Inputs' },
  { type: 'email', label: TYPE_LABEL.email, group: 'Inputs' },
  { type: 'phone', label: TYPE_LABEL.phone, group: 'Inputs' },
  { type: 'url', label: TYPE_LABEL.url, group: 'Inputs' },
  { type: 'number', label: TYPE_LABEL.number, group: 'Inputs' },
  { type: 'address', label: TYPE_LABEL.address, group: 'Inputs' },
  { type: 'date', label: TYPE_LABEL.date, group: 'Inputs' },
  { type: 'file_upload', label: TYPE_LABEL.file_upload, group: 'Inputs' },
  { type: 'single_choice', label: TYPE_LABEL.single_choice, group: 'Choices' },
  { type: 'multi_choice', label: TYPE_LABEL.multi_choice, group: 'Choices' },
  { type: 'dropdown', label: TYPE_LABEL.dropdown, group: 'Choices' },
  { type: 'picture_choice', label: TYPE_LABEL.picture_choice, group: 'Choices' },
  { type: 'yes_no', label: TYPE_LABEL.yes_no, group: 'Choices' },
  { type: 'scale', label: TYPE_LABEL.scale, group: 'Choices' },
  { type: 'nps', label: TYPE_LABEL.nps, group: 'Choices' },
  { type: 'ranking', label: TYPE_LABEL.ranking, group: 'Choices' },
  { type: 'matrix', label: TYPE_LABEL.matrix, group: 'Choices' },
  // Wave C (ADR-065): things a phone captures on the spot.
  { type: 'photo_checklist', label: TYPE_LABEL.photo_checklist, group: 'Capture' },
  { type: 'image_pin', label: TYPE_LABEL.image_pin, group: 'Capture' },
  { type: 'voice_note', label: TYPE_LABEL.voice_note, group: 'Capture' },
  { type: 'location', label: TYPE_LABEL.location, group: 'Capture' },
  { type: 'availability', label: TYPE_LABEL.availability, group: 'Capture' },
  { type: 'statement', label: TYPE_LABEL.statement, group: 'Other' },
  { type: 'legal', label: TYPE_LABEL.legal, group: 'Other' },
  { type: 'signature', label: TYPE_LABEL.signature, group: 'Other' },
  { type: 'review', label: TYPE_LABEL.review, group: 'Other' },
  { type: 'welcome', label: TYPE_LABEL.welcome, group: 'Screens' },
  { type: 'thanks', label: TYPE_LABEL.thanks, group: 'Screens' },
];
